[package]
name = "SOEM-sys"
version = "0.1.0"
authors = ["Matwey V. Kornilov <matwey.kornilov@gmail.com>"]
license = "GPL-2.0-only"
description = "Rust FFI bindings for SOEM"

[build-dependencies]
cmake = "0.1"
bindgen = "0.42.2"
